### ISSUE TITLE
server armor backend is down

### ISSUE THREAD

**Issue by Katakurinna** [Pho3niX90/uptime#43]
Hello there, server armour is down at this moment, it takes at least 2 hours.
![image](https://user-images.githubusercontent.com/43810296/151848462-673a1114-443a-47b7-992a-ce30e57ff104.png)

**Comment by Katakurinna** [comment]
![image](https://user-images.githubusercontent.com/43810296/151848670-66b260d9-bf37-4033-bb03-b798f06515a7.png)
This includes check users profiles.

**Comment by Pho3niX90** [comment]
Thanks for the report. It's up again
